### PR TITLE
Associate Cloud Engineering Learning Plan

### PR DESCRIPTION
**Pull request by Kevinmuriuki**
I added content for the cloud-learning file, thought was helpful... Feel free to check it out. Thank you.

### CODE REVIEW

**Comment by udoyen** [comment]
The 15th date may not be correct as this phase is 7weeks from the 16th of July ... Please confirm the source of the end date. @Kevinmuriuki

**Review by udoyen — CHANGES_REQUESTED** [review]
The end date needs to be checked as mine falls on the 5th to 7th of September. Note the phase I is 7 weeks (49 days) from 16th of July

**Comment by matthewrungwe** [comment]
Hi there, @Kevinmuriuki 👋.

- I saw the changes you made to the Cloud Learning Plan. 
- I also saw your word changes, good eye 👍.

I will merge your changes. I will get @udoyen to check.


Thank you for your contribution. 👍.

**Comment by matthewrungwe** [comment]
> The end date needs to be checked as mine falls on the 5th to 7th of September. Note the phase I is 7 weeks (49 days) from 16th of July

Can we `merge` the changes while we confirm the date?

**Pull request merged**
